#!/bin/sh

set -eu

echo "http://cdn.openbsd.org/pub/OpenBSD/" > /etc/installurl

pkg_add ansible git
git clone https://github.com/charlesrocket/openbsd-station
cd openbsd-station
ansible-galaxy install -r requirements.yml
ansible-playbook openbsd.yml --ask-become-pass
