#!/bin/sh

set -eu

pkg_add -I ansible git
git clone https://github.com/charlesrocket/openbsd-station
cd openbsd-station
ansible-galaxy install -r requirements.yml
ansible-playbook openbsd.yml --ask-become-pass
