---
# Settings
timezone: America/Los_Angeles

# Dotfiles
dotfiles_repo: https://github.com/charlesrocket/dotfiles.git
dotfiles_repo_version: obsd-station
dotfiles_repo_accept_hostkey: true
dotfiles_repo_force: true
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_home: ~
dotfiles_files:
  - .config/mc/ini
  - .gitconfig
  - .xsession
  - .zshrc

# Configuration
hostname:

# Keep packages up to date
upgrade_packages: true

# Packages
pkg_packages:
  - alacritty
  - clamav
  - cmake
  - curl
  - direnv
  - editorconfig-core-c
  - emacs
  - fdupes
  - figlet
  - firefox-esr
  - fzf
  - gawk
  - gcc
  - gimp
  - git
  - gmake
  - gnupg
  - gnuplot
  - htop
  - iftop
  - imv
  - llvm
  - lynis
  - lynx
  - mc
  - meson
  - mp3blaster
  - mpv
  - nikto
  - ninja
  - nmap
  - pcsc-tools
  - pv
  - pwgen
  - python3
  - ripgrep
  - rust
  - scdoc
  - screen
  - shellcheck
  - tig
  - transmission
  - tree
  - unibilium
  - unzip
  - vlc
  - wget
  - ykpers
  - zsh
