---
# Settings
timezone: America/Los_Angeles

# Dotfiles
dotfiles_repo: https://github.com/charlesrocket/dotfiles.git
dotfiles_repo_version: obsd-station
dotfiles_repo_accept_hostkey: true
dotfiles_repo_force: true
dotfiles_repo_local_destination: "~/git/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .config/awesome/rc.lua
  - .config/awesome/theme.lua
  - .config/fontconfig/fonts.conf
  - .config/gtk-3.0/settings.ini
  - .config/mc/ini
  - .doom.d/config.el
  - .doom.d/init.el
  - .doom.d/packages.el
  - .gitconfig
  - .kshrc
  - .profile
  - .xsession
  - .zshrc

# Git
git_repo_destination: "~/git/git"
git_helper_directory: "~/bin"
git_netrc_helper: true

# Configuration
xenodm: true

# Keep system up to date
patch_system: true

# Packages
pkg_packages:
  - alacritty
  - apl-fonts
  - awesome
  - clamav
  - cmake
  - curl
  - direnv
  - editorconfig-core-c
  - fdupes
  - feh
  - figlet
  - firefox-esr
  - font-awesome
  - fzf
  - gawk
  - gimp
  - git
  - gmake
  - gnupg
  - gnuplot--
  - htop
  - iftop
  - imv
  - llvm
  - lxappearance
  - lynis
  - lynx
  - mc
  - meson
  - mp3blaster
  - mpv
  - nikto
  - ninja
  - nmap
  - pcsc-tools
  - pv
  - pwgen
  - python3
  - ripgrep
  - rust
  - scdoc
  - screen--
  - shellcheck
  - spleen
  - tig
  - transmission
  - tree
  - unibilium
  - unzip--
  - upower
  - vlc
  - wget
  - xclip
  - xdotool
  - ykpers
  - zsh
