---
# Settings
timezone: America/Los_Angeles

# Dotfiles
dotfiles_repo: https://github.com/charlesrocket/dotfiles.git
dotfiles_repo_version: obsd-station
dotfiles_repo_accept_hostkey: true
dotfiles_repo_force: true
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .config/mc/ini
  - .gitconfig
  - .xsession
  - .zshrc

# Configuration
hostname:
username: xxx

# Keep packages up to date
upgrade_packages: true

# Packages
pkg_packages:
  - alacritty
  - clamav
  - cmake
  - curl
  - direnv
  - doas
  - droid-fonts-ttf
  - editorconfig-core-c
  - emacs
  - fdupes
  - fd-find
  - ffuf
  - figlet
  - firefox-esr
  - fzf
  - gawk
  - gcc
  - gimp
  - git
  - gmake
  - gnuls
  - gnupg
  - gnuplot
  - gzip
  - hashcat
  - htop
  - httping
  - hwstat
  - iftop
  - imv
  - less
  - llvm
  - lolcat
  - lynis
  - lynx
  - masscan
  - mc
  - meson
  - mp3blaster
  - mpv
  - netcat
  - nikto
  - ninja
  - nmap
  - pcsc-tools
  - pv
  - pwgen
  - python3
  - rbenv
  - ripgrep
  - rkhunter
  - rust
  - scdoc
  - screen
  - seatd
  - shellcheck
  - tig
  - tmux
  - transmission
  - tree
  - unibilium
  - unzip
  - vagrant
  - vlc
  - wget
  - whois
  - wlogout
  - ykpers
  - zmap
  - zsh
