---
- name: OpenBSD Station
  hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Load config.yml
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: common

    - role: charlesrocket.dotfiles

    - role: pkg
      become: true

    - role: sys
      become: true
