---
- name: Ensure packages are installed
  community.general.openbsd_pkg:
    state: present
    name: "{{ packages }}"
  vars:
    packages: "{{ pkg_packages }}"

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
    strategy: all
