---
- name: Apply all available system patches
  community.general.syspatch:
  become: true
  when: patch_system

- name: Edit user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: staff,wheel
    append: true
  become: true

- name: Check xenodm
  ansible.builtin.command: rcctl check xenodm
  register: xenodm_check
  when: xenodm
  failed_when: xenodm_check.rc == 2
  changed_when: false

- name: Enable xenodm
  ansible.builtin.command: rcctl enable xenodm
  when: xenodm_check.stdout != "xenodm(ok)"
  become: true
