---
- name: Upgrade installed packages
  community.general.openbsd_pkg:
    name: "*"
    state: latest
  become: true
  when: upgrade_packages

- name: Apply all available system patches
  community.general.syspatch:
  become: true
  when: patch_system

- name: Edit user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
    groups: wheel
    append: true
  become: true

- name: Install ohmyzsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"
