---
- name: Apply all available system patches
  community.general.syspatch:
  become: true
  when: patch_system

- name: Edit user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: staff,wheel
    append: true
  become: true

- name: Enable xenodm
  ansible.builtin.command: rcctl enable xenodm
  when: xenodm
  become: true
