---
- name: Upgrade installed packages
  community.general.openbsd_pkg:
    name: "*"
    state: latest
  become: true
  when: upgrade_packages

- name: Copy Lynis profile
  ansible.builtin.copy:
    src: desktop.prf
    dest: /usr/local/etc/lynis/desktop.prf
    owner: root
    mode: 0644
  become: true

- name: Copy MOTD
  ansible.builtin.copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: true

- name: Install MOTD
  ansible.builtin.cron:
    name: Update MOTD
    special_time: reboot
    job: /etc/motd.sh > /etc/motd.template
    user: root
    state: present
  become: true
