---

name: Ansible Lint

"on":
  pull_request:
  push:
  schedule:
    - cron: "0 11 13 */2 *"

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@main
