name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Test playbook
      id: test
      uses: vmactions/openbsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg_add ansible git

        run: |
          git clone -b ${GITHUB_REF##*/} https://github.com/charlesrocket/openbsd-station /tmp/openbsd-station
          cp /tmp/openbsd-station/test/config.yml /tmp/openbsd-station/config.yml
          echo "permit nopass keepenv :wheel" > /etc/doas.conf
          adduser -noconfig -group USER -batch foo wheel
          chown -R foo:foo /tmp/openbsd-station
          su -l foo -c 'cd /tmp/openbsd-station && test/idempotence_test.sh'
