name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Test playbook
      id: test
      uses: vmactions/openbsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg_add ansible sudo

        run: |
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers
          adduser -noconfig -m -batch foo wheel 'Bar'
          chown -R foo:foo .
          su -l foo -c 'test/idempotence_test.sh'
          cp test/config.yml config.yml
          test/idempotence_test.sh
