name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Test playbook
      id: test
      uses: vmactions/openbsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg_add ansible

        run: test/idempotence_test.sh
