name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Test playbook
      id: test
      uses: vmactions/openbsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg_add ansible git

        run: |
          adduser -batch foo wheel 'Bar'
          cp test/config.yml config.yml
          test/idempotence_test.sh
