---

name: Test

"on":
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test playbook
        id: test
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg_add ansible git
          run: |
            git clone -b ${GITHUB_REF##*/} \
              https://github.com/charlesrocket/openbsd-station \
              /tmp/openbsd-station
            cp /tmp/openbsd-station/test/config.yml \
              /tmp/openbsd-station/config.yml
            echo "permit nopass keepenv :wheel" > /etc/doas.conf
            adduser -noconfig -group USER -batch foo wheel
            chown -R foo:foo /tmp/openbsd-station
            su -l foo -c 'cd /tmp/openbsd-station && test/idempotence_test.sh'
